### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ManuDay** [MoravianLion/Drift-Script#2]
So I can tell you a bug because I've been following this script for a long time and have tested it with friends. If one person gets off with the TCS and another person gets on, this system is actually on and not off for that person as it should be. This gives this car an extreme acceleration boost and drives over 400

**Comment by MoravianLion** [comment]
This only happens when another vehicle handling related script is interfering. 

We use this script for about 1,5 years now and never had this issue, in cases that you described above.

Try to replicate it on a test server with your friend, with only the Drift script and you will see for yourself. It will work as intended.

If by any chance that happens, that you have to adjust either handling for that specific vehicle or adjust values in the Drift script to your handlings in general. These default values have been set for our handling model. If it would bug out with multiple cars on your server, you need to adjust Drift script accordingly. While in the game, open F8 client console and check which value is ridiculously high in contrast to others. That's the one you want to take care of.

**Comment by ManuDay** [comment]
I'm sorry if I assume you, or maybe you get it wrong, what do I know, the problem only happens if, for example, you get out with deactivated TCS then another player comes who gets into this vehicle and drives normally without turning it off or on if he has this exaggerated boost, feel free to try it out

**Comment by fantomeus** [comment]
same bug for me

**Comment by EleDos** [comment]
This bug seems to have not been fixed. Has anyone found a way to correct it?

**Comment by MoravianLion** [comment]
Added loop for every player to check mode the vehicle they're driving is. Not ideal, but should work.
